### ISSUE TITLE
dapple init - Syntax Error: Unexpected token {

### ISSUE THREAD

**Issue by dotnetspec** [dapphub/dapple#394]
Hi,

I've installed dapple with dependencies and without apparent issue as per [these instructions](https://dapple.readthedocs.io/en/master/install/)
on my Linux Mint 18 machine

However, I get this error on 'dapple init' and/or 'sudo dapple init'

![unexpected token](https://cloud.githubusercontent.com/assets/27340988/25467915/5408c8be-2b44-11e7-84bd-cb1959ab8e2a.png)

The comment at state.js:31 states '// TODO - this may be hacky. initWorkspace shouldnt be called in the first place if no workspace is found.'

But I don't know what to do about it ... comment initWorkspace out?

Thanks,

**Comment by nmushegian** [comment]
dapple has been superceded by https://github.com/dapphub/dapp, sorry about that!

**Comment by dotnetspec** [comment]
Ok, glad I asked!
Thanks ...
