### ISSUE TITLE
question: dapple vs. dapp?

### ISSUE THREAD

**Issue by warren-bank** [dapphub/dapple#396]
Hi. This is kind of a high-level question.. but I was just wondering whether [dapple](https://github.com/dapphub/dapple) will eventually be deprecated and replaced by [dapp](https://github.com/dapphub/dapp)?

There seems to be a lot of functional overlap between the two projects, and I'm not really sure how they fit together. I suppose I'm mainly asking for some clarity in that regard.

I'm very new to Ethereum. I've read as much documentation as I can find. Now I'm trying to get a better grip on the tools and ecosystem.

Given that my level of experience and understanding is less than those reading this.. I'm going to quickly compare and contrast features of the two projects, and I ask that I please be corrected where I'm mistaken..

They both do package management and have a testing framework:
* package management in `dapple` is done via a name-registry contract in Ethereum (name and version -> multihash) combined with IPFS (multihash represents the Merkle root of content-addressable data)
* package management in `dapp` is currently done via git submodules, though the intention is to migrate to EthPM (when ready).. which will also use IPFS for data storage
* the testing framework in `dapp` is based on [`dapple-quicktest`](https://github.com/dapphub/dapple-quicktest) and should give a huge performance boost, in addition to providing much more detailed information about the origin of nested throws
* the testing framework in `dapple` can be run against either a new blockchain, or a fork of any existing blockchain.. which is a *very* powerful feature to test integration with previously deployed contracts

On the other hand:
* `dapple` has `DappleScript`, which can:
  * run migrations
  * run shell scripts and synchronously read the output into a variable
  * write data to the Dappfile
  * other magic..

Are they supposed to be used together in combination, or is one (intended to become) a more powerful superset of the other?

Sorry for being a n00b. Thanks for reading :)

**Comment by warren-bank** [comment]
some additional observations, thoughts, ramblings..

in terms of migration scripts:
* `dapp` uses `seth` as a command-line tool to make JSON RPC calls
* Migration scripts can (presumably) be written directly in bash, making use of `seth`

in terms of the ability to fork blockchains:
* It would actually be really nice if this functionality could be split into a standalone JSON RPC server, which could then be used by any abstraction layer (ex: `seth`, `web3.js`, etc..)
* When no forking is needed, `testrpc` can be used.
* When forking is needed, this server is a drop-in replacement.
* I assume that forking of a public blockchain is a fairly lightweight operation, since each block header references a snapshot of the complete state of the blockchain (at the time it was mined). As such, it would seem all that's needed to perform a fork would be:
  * a network connection to a trusted peer running a full client
  * to download this one particular block header
  * to download all data stored in Merkle trees (ie: state, transaction, receipts) having roots contained in this block header, or to proxy requests for this data to the full peer using light-client APIs

**Comment by nmushegian** [comment]
@warren-bank I really have to congratulate you on being able to wade through this mess with just the docs we have out there.

`dapp` has effectively deprecated `dapple`. We could make it clearer that all new users should use `dapp`. 

> dapple has DappleScript, which can ...

DappleScript was multiple r&d efforts in one project which resulted in something that looks like frankenstein. Do not recommend.

> Migration scripts can (presumably) be written directly in bash, making use of seth

Yep. In practice we are not even close to needing structured/typed deploy languages.

> re: forking

Dapple chain forking was experimental and created before the client devs picked it up as a feature request

> re: packages

Package management and namespacing both grew/merged into collaborative projects, now ens.domains and ethpm.org

**Comment by warren-bank** [comment]
are you kidding?.. that's like Superman giving a pat on the back to the bumbling dummy he just saved :)

You guys are amazing! Thanks for all your hard work.. and for helping me to better understand the current state (and near-term direction) of these projects.

I'll be installing `dapp` right now... :)
